### ISSUE TITLE
No configuration available under 4.6.9

### ISSUE THREAD

**Issue by kasiawaka** [adixon/ca.civicrm.contributionrecur#1]
Hello, 
thanks for the extension!
Wondering if this extension is 4.6.x compatible? After enabling it, there is no configuration option that should be under Admin -> CiviContribute -> Recurring Contribution Settings and the link http://example.com/civicrm/admin/contribute/recursettings opens Manage Contributions Page screen instead of form to configure the recurring payments. Thanks for any info on this

**Comment by adixon** [comment]
Sounds like i need to check the new 4.6 way for doing settings, or else your menu needs to be rebuilt. I haven't tested it with 4.6, only 4.5 and 4.4, but I'll need to get it working for 4.6 soon enough.

**Comment by kasiawaka** [comment]
I've cleared cache and rebuilt menus, no go. Please let me know if I can help in any way.

**Comment by adixon** [comment]
Okay, I've been doing some development recently, I'll let you know when all that is up to date and then if you refresh your copy it should work.

**Comment by alanpuccinelli** [comment]
Any headway on this? Would love to see it work on 4.6/4.7 too

**Comment by adixon** [comment]
I just tested it with Drupal 7 CiviCRM 4.6.12, latest version of this extension, and I'm not having this issue. What versions are you using? I have had some challenges with the navigationMenu and conflicts from other extensions before, so also tell me what other extensions you might have enabled.

**Comment by kasiawaka** [comment]
I still have this issue as well. CiviCRM 4.6.10, extensions: 
- Recurring Contributions (ca.civicrm.contributionrecur) 1.0
- iATS Payments (com.iatspayments.civicrm) 1.4.2
- CDN Tax Receipts (org.civicrm.cdntaxreceipts) 1.2
- CiviVolunteer (org.civicrm.volunteer) 4.5-1.4.1

I'm about to upgrade to CiviCRM 4.6.12, will report if anything changes.

**Comment by adixon** [comment]
Okay - I'm going to guess that it's one of your other extensions clobbering the navMenu entry. Can you test by disabling all your extensions and then just renable the recurring contribution one?

**Comment by adixon** [comment]
I've just updated the code used to add the navigation menu item d7288bfd9dd8d0675f17bd8aeb99239569ea6c46
That might prevent the collisions/clobbering you were experiencing.
