### ISSUE TITLE
Question about mapping with multiples

### ISSUE THREAD

**Issue by zkrebs** [adixon/ca.civicrm.contributionrecur#4]
In the documentation you state:

> mapping=financial_type_id:membership_type_id:membership_financial_type_id
> dateLimit=(something that strtotime can read)
> 
> The type_id's for the mapping can be multiple if you like, separated by commas.

I have one financial_type_id {32}, a few membership_type_id {25,26,27,28,29,30}, and one membership financial_type_id {32} which they all share.

Would it be configure the job as such?
mapping=32:25,26,27,28,29,30:32
dateLimit=today

When the job runs, would it match all recurring contributions with financial type 32 to their associated membership record?

Thank you!

**Comment by adixon** [comment]
No, I think that mapping would be 32:25:32, 32:25:32, etc.

Yes, it should apply the contributions towards any matching memberships. It won't create the memberships.  Applying the contributions means an entry in the contribution_membership_payment table (I might have the name of that table wrong), and potentially an advance of the membership expiry date.

**Comment by zkrebs** [comment]
As a followup - I was able to use it successfully to match unlinked contributions, but I did not see it update the member expiry date. In the extension settings, we have "Select an activity type for implicit membership renewals", but we do not have "Membership Renewal" available, only custom types it seems. If I define a custom type, it will create an activity record, but not advance the expiry date. Have I misconfigured it somehow?

**Comment by adixon** [comment]
Maybe, but hard to tell. The code the (potentially) increments the member expiry is here:
https://github.com/adixon/ca.civicrm.contributionrecur/blob/master/CRM/Contributionrecur/MembershipImplicit.php

**Comment by zkrebs** [comment]
Ah, thanks so much! I think line 52-53 is why it didn't trigger because a staff member updated the status/end date manually before this ran. 

```
for a grace/expired membership, figure out start and end dates of the membership and update it
    if ($membership['status_id'] > 2) {
```

**Comment by zkrebs** [comment]
Just reporting back - it worked like a charm. Linked the contributions and updated the membership end date. Thank you!
